# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 风之旅人
brief-intro: Android Dev Engineer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://javakam.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username:  javakam
email: jooybao@foxmail.com
weibo_username:
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer:
toc: true
# comments
# two ways to comment, only choose one, and use your own short name
# 评论插件，任选其一，使用自己的 short_name
duoshuo_shortname:
disqus_shortname:
# https://github.com/gitalk/gitalk#install
gitalk_shortname: javakam
# https://github.com/meteorlxy/vssue
vssue_shortname:


# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: bb0a2560fdb5815c4547758594993e5b # cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: #  UA-72449510-4 # google 分析追踪id

# Build settings  https://highlightjs.org  railscasts  zenburn androidstudio
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 8
